version: '3.5'

networks:
  default:
    external:
      name: thedirection

services:

  web:
    image: ghcr.io/posterstock/thedirection:latest
    restart: always
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik
      - traefik.http.routers.thedirection.entrypoints=http
      - traefik.http.routers.thedirection.rule=Host(`thedirection.org`)
      - traefik.http.routers.thedirection.middlewares=thedirection-https
      - traefik.http.middlewares.thedirection-https.redirectscheme.scheme=https
      - traefik.http.routers.thedirection-https.entrypoints=https
      - traefik.http.routers.thedirection-https.rule=Host(`thedirection.org`)
      - traefik.http.routers.thedirection-https.tls=true
      - traefik.http.routers.thedirection-https.tls.certresolver=leresolver
