name: Build and Publish Docker Images

on:
  push:
    branches: [ master ]

env:
  REPO_URL: "git@github.com-thedirection:posterstock/thedirection.git"
  REPO_REF: master
  PROJECT_PATH: "/opt/thedirection.org"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/posterstock/thedirection:latest

  deploy:
    runs-on: ubuntu-latest
    needs:
      - publish
    steps:
      - name: Pulling updates from project repo
        uses: garygrossgarten/github-action-ssh@0.7.0
        with:
          command: |
            if [[ -d "${{ env.PROJECT_PATH }}" ]];then
              cd "${{ env.PROJECT_PATH }}"
              git checkout "${{ env.REPO_REF }}"
              git reset --hard HEAD && git pull
            else
              git clone "${{ env.REPO_URL }}" -b "${{ env.REPO_REF }}" "${{ env.PROJECT_PATH }}"
            fi
            printf "${{ secrets.GITHUB_TOKEN }}" | docker login --username ${{ github.actor }} --password-stdin ghcr.io
            docker-compose pull
            docker-compose up --detach
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          privateKey: ${{ secrets.DEPLOY_KEY }}
